version: "2"

run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

formatters:
  enable:
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/hortator-ai/Hortator
