run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/michael-niemand/Hortator

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
