run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/michael-niemand/Hortator
