version: 2

builds:
  - id: hortator
    main: ./cmd/hortator
    binary: hortator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/hortator-ai/Hortator/cmd/hortator/cmd.Version={{.Version}}
      - -X github.com/hortator-ai/Hortator/cmd/hortator/cmd.GitCommit={{.Commit}}
      - -X github.com/hortator-ai/Hortator/cmd/hortator/cmd.BuildTime={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "hortator_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  use: github-native

release:
  github:
    owner: hortator-ai
    name: Hortator
  prerelease: auto
