# Test: AgentPolicy & Role Override Precedence
#
# Validates the three-tier override model:
#   1. Helm values (cluster-wide defaults)
#   2. AgentRole (per-role overrides)
#   3. AgentTask spec (per-task overrides — most specific wins)
#
# Also tests AgentPolicy enforcement:
#   - Tasks must comply with all matching policies
#   - Policy restricts capabilities, budget, tier, images
#   - DeniedCapabilities overrides AllowedCapabilities
#
# Expected behavior:
#   - Task inherits defaults from Helm values
#   - Role overrides applicable defaults
#   - Task-level spec overrides role defaults
#   - Policy violations cause task rejection (Pending → Failed)
#   - Denied capabilities block even if task requests them
#
# Prerequisites:
#   - Anthropic API key secret
---
# Restrictive namespace policy
apiVersion: core.hortator.ai/v1alpha1
kind: AgentPolicy
metadata:
  name: production-policy
  namespace: hortator-test-policy
  labels:
    hortator.ai/test-suite: policy
spec:
  # Only allow specific capabilities
  allowedCapabilities:
    - shell
    - web-fetch
    - spawn
  # Explicitly deny dangerous capabilities (overrides allowed)
  deniedCapabilities:
    - web-fetch                  # Even though it's in allowed, denied wins
  # Restrict container images
  allowedImages:
    - "ghcr.io/hortator-ai/hortator/*"
    - "ghcr.io/hortator-ai/hortator/*"
  # Budget ceiling
  maxBudget:
    maxCostUsd: "2.00"
    maxTokens: 200000
  # Only legionary and centurion — no tribunes in this namespace
  maxTier: centurion
  # Concurrency limit
  maxConcurrentTasks: 10
  # Force PII scanning
  requirePresidio: true
  # Network egress restrictions
  egressAllowlist:
    - host: "api.anthropic.com"
      ports: [443]
    - host: "10.0.0.0/8"        # Allow internal cluster traffic
---
# Role with its own defaults — some will be overridden by the task
apiVersion: core.hortator.ai/v1alpha1
kind: ClusterAgentRole
metadata:
  name: cautious-coder
  labels:
    hortator.ai/test-suite: policy
spec:
  description: >-
    A conservative coding agent with restricted capabilities.
    Used to test override precedence.
  defaultModel: claude-sonnet-4-20250514
  tools:
    - shell
  rules:
    - "Always run tests before completing"
    - "Never modify files outside /workspace"
---
# Task that complies with the policy — should succeed
apiVersion: core.hortator.ai/v1alpha1
kind: AgentTask
metadata:
  name: policy-compliant-task
  namespace: hortator-test-policy
  labels:
    hortator.ai/test-suite: policy
    hortator.ai/test-case: compliant
  annotations:
    hortator.ai/description: "Task within policy bounds — should succeed"
spec:
  role: cautious-coder
  tier: legionary                # Within maxTier:centurion
  prompt: "Write a hello world program. Save to /outbox/result.json."
  model:
    name: claude-sonnet-4-20250514
    endpoint: https://api.anthropic.com/v1
    apiKeyRef:
      secretName: anthropic-api-key
      key: api-key
  capabilities:
    - shell                      # Allowed by policy
  budget:
    maxCostUsd: "0.50"           # Under policy maxBudget
  timeout: 180
  # Task-level Presidio override — stricter than policy default
  presidio:
    scoreThreshold: 0.3
    action: hash
---
# Task that VIOLATES the policy — should be rejected
apiVersion: core.hortator.ai/v1alpha1
kind: AgentTask
metadata:
  name: policy-violation-tier
  namespace: hortator-test-policy
  labels:
    hortator.ai/test-suite: policy
    hortator.ai/test-case: violation-tier
  annotations:
    hortator.ai/description: "Tribune tier in centurion-max namespace — should be rejected"
spec:
  role: cautious-coder
  tier: tribune                  # VIOLATION: policy maxTier is centurion
  prompt: "This task should never run — it violates the tier policy."
  model:
    name: claude-sonnet-4-20250514
    endpoint: https://api.anthropic.com/v1
    apiKeyRef:
      secretName: anthropic-api-key
      key: api-key
  capabilities:
    - spawn
  budget:
    maxCostUsd: "1.00"
  timeout: 300
---
# Task that requests a denied capability — should be rejected
apiVersion: core.hortator.ai/v1alpha1
kind: AgentTask
metadata:
  name: policy-violation-capability
  namespace: hortator-test-policy
  labels:
    hortator.ai/test-suite: policy
    hortator.ai/test-case: violation-capability
  annotations:
    hortator.ai/description: "Requests web-fetch which is in deniedCapabilities — should be rejected"
spec:
  tier: legionary
  prompt: "This task requests a denied capability."
  model:
    name: claude-sonnet-4-20250514
    endpoint: https://api.anthropic.com/v1
    apiKeyRef:
      secretName: anthropic-api-key
      key: api-key
  capabilities:
    - shell
    - web-fetch                  # VIOLATION: in deniedCapabilities
  budget:
    maxCostUsd: "0.25"
  timeout: 120
---
# Task that exceeds budget policy — should be rejected
apiVersion: core.hortator.ai/v1alpha1
kind: AgentTask
metadata:
  name: policy-violation-budget
  namespace: hortator-test-policy
  labels:
    hortator.ai/test-suite: policy
    hortator.ai/test-case: violation-budget
  annotations:
    hortator.ai/description: "Budget exceeds policy maxBudget — should be rejected"
spec:
  tier: legionary
  prompt: "This task requests too much budget."
  model:
    name: claude-sonnet-4-20250514
    endpoint: https://api.anthropic.com/v1
    apiKeyRef:
      secretName: anthropic-api-key
      key: api-key
  budget:
    maxCostUsd: "10.00"          # VIOLATION: policy max is $2.00
    maxTokens: 500000            # VIOLATION: policy max is 200000
  timeout: 300
