# Test: Retry Policy with Exponential Backoff
#
# Validates the hybrid retry semantics:
#   - Transient failures (pod crash, exit code 1) → auto-retry with backoff
#   - Retry exhaustion → terminal Failed phase
#   - Successful task with retry config → completes normally (no spurious retries)
#
# The retry-transient test uses a prompt that instructs the agent to exit
# with code 1 on the first attempt (simulating a transient crash), then
# succeed on retry. The operator detects exit code 1 as transient and retries.
#
# Prerequisites:
#   - Anthropic API key secret in namespace
---
# Test: Transient failure recovery with backoff
#
# Strategy: The agent is told to check for a marker file. If absent, create
# it and exit 1 (simulating crash). On retry the marker exists → succeed.
# This reliably triggers the retry path.
apiVersion: core.hortator.ai/v1alpha1
kind: AgentTask
metadata:
  name: retry-transient-test
  namespace: hortator-test
  labels:
    hortator.ai/test-suite: retry
    hortator.ai/test-case: transient-recovery
  annotations:
    hortator.ai/description: "Tests transient failure recovery with exponential backoff"
spec:
  prompt: |
    You are a test agent. Execute this shell script exactly:

    ```bash
    if [ -f /tmp/attempt-marker ]; then
      echo "Marker found — this is a retry. Succeeding."
      echo '{"status":"completed","summary":"Recovered after retry"}' > /outbox/result.json
      exit 0
    else
      touch /tmp/attempt-marker
      echo "First attempt — simulating transient crash"
      exit 1
    fi
    ```

    Run the script above verbatim. Do not modify it.
  tier: legionary
  model:
    name: claude-sonnet-4-20250514
    endpoint: https://api.anthropic.com/v1
    apiKeyRef:
      secretName: anthropic-api-key
      key: api-key
  retry:
    maxAttempts: 3
    backoffSeconds: 10
    maxBackoffSeconds: 60
  timeout: 180
  capabilities:
    - shell
  budget:
    maxCostUsd: "0.50"
---
# Test: Retry exhaustion — all attempts fail → terminal Failed
#
# Strategy: Use an invalid API key so every attempt fails with an API error.
# The runtime calls die() which exits 1 (transient), so the operator retries.
# After maxAttempts, the task should reach Failed phase.
apiVersion: core.hortator.ai/v1alpha1
kind: AgentTask
metadata:
  name: retry-exhaustion-test
  namespace: hortator-test
  labels:
    hortator.ai/test-suite: retry
    hortator.ai/test-case: exhaustion
  annotations:
    hortator.ai/description: "Tests that retry exhaustion results in terminal Failed phase"
spec:
  prompt: |
    Say hello.
  tier: legionary
  model:
    name: claude-sonnet-4-20250514
    endpoint: https://api.anthropic.com/v1
    apiKeyRef:
      secretName: invalid-api-key-does-not-exist
      key: api-key
  retry:
    maxAttempts: 2
    backoffSeconds: 5
    maxBackoffSeconds: 15
  timeout: 60
  capabilities: []
---
# Test: Successful task with retry config — no spurious retries
#
# A normal task with retry configured should complete on first attempt
# without triggering any retry logic. Verifies retries don't fire on success.
apiVersion: core.hortator.ai/v1alpha1
kind: AgentTask
metadata:
  name: retry-success-no-retry
  namespace: hortator-test
  labels:
    hortator.ai/test-suite: retry
    hortator.ai/test-case: success-no-retry
  annotations:
    hortator.ai/description: "Verifies successful tasks don't trigger retry logic"
spec:
  prompt: |
    Write "Hello from retry test — first attempt success" to /outbox/result.json.
  tier: legionary
  model:
    name: claude-sonnet-4-20250514
    endpoint: https://api.anthropic.com/v1
    apiKeyRef:
      secretName: anthropic-api-key
      key: api-key
  retry:
    maxAttempts: 5
    backoffSeconds: 10
  timeout: 120
  capabilities:
    - shell
  budget:
    maxCostUsd: "0.25"
