# Demo: Autonomous Multi-Tier Hierarchy
#
# Showcases the agent awareness feature (P0+P1):
#   - Roles have descriptions, rules, and anti-patterns
#   - Tribune discovers available roles via HORTATOR_AVAILABLE_ROLES
#   - Tribune autonomously decides WHO to delegate to and WHAT to delegate
#   - No scripted work breakdown — the agent plans its own approach
#
# This replaces the old "puppet orchestration" pattern where the prompt
# had to explicitly script every delegation step.
#
# Before (old pattern):
#   prompt: "1. Spawn api-team-lead centurion  2. Centurion spawns endpoint-coder..."
#
# After (autonomous):
#   prompt: "Build a TODO API with these endpoints. Delegate as you see fit."
#
# Prerequisites:
#   - Anthropic API key secret: kubectl create secret generic anthropic-api-key \
#       --from-literal=api-key=$ANTHROPIC_API_KEY
---
# Roles — the agent discovers these at runtime via the role registry.
# Each role is self-describing: description tells WHAT it does,
# rules tell HOW it should behave, antiPatterns tell what to AVOID.
apiVersion: core.hortator.ai/v1alpha1
kind: ClusterAgentRole
metadata:
  name: project-architect
  labels:
    hortator.ai/demo: multi-tier
spec:
  description: >-
    Strategic project lead. Decomposes complex tasks into subtasks,
    delegates to specialists, reviews and consolidates results into
    a final deliverable.
  tierAffinity: tribune
  defaultModel: claude-sonnet-4-20250514
  tools:
    - spawn
    - shell
    - web-fetch
  rules:
    - "Analyze the full scope before delegating anything"
    - "Assign each subtask to the most appropriate role"
    - "Review all child results for quality before consolidating"
    - "Produce a final summary with clear structure"
  antiPatterns:
    - "Don't do implementation work yourself — delegate to specialists"
    - "Don't spawn more than 5 concurrent children"
    - "Don't skip the review step"
---
apiVersion: core.hortator.ai/v1alpha1
kind: ClusterAgentRole
metadata:
  name: api-team-lead
  labels:
    hortator.ai/demo: multi-tier
spec:
  description: >-
    Coordinates API implementation. Breaks down API specs into
    individual endpoints, delegates implementation and testing,
    integrates results into a working API.
  tierAffinity: centurion
  defaultModel: claude-sonnet-4-20250514
  tools:
    - spawn
    - shell
  rules:
    - "Define the API contract (routes, methods, schemas) before delegating"
    - "Ensure consistent error handling across all endpoints"
    - "Run integration tests after collecting all endpoint implementations"
  antiPatterns:
    - "Don't implement endpoints yourself unless there's only one"
    - "Don't let children define their own URL patterns — provide the contract"
---
apiVersion: core.hortator.ai/v1alpha1
kind: ClusterAgentRole
metadata:
  name: endpoint-coder
  labels:
    hortator.ai/demo: multi-tier
spec:
  description: >-
    Implements individual API endpoints with tests. Focused executor
    that writes clean, tested code for a single endpoint or module.
  tierAffinity: legionary
  defaultModel: claude-sonnet-4-20250514
  tools:
    - shell
  rules:
    - "Write unit tests before implementation"
    - "Follow RESTful conventions (proper status codes, JSON responses)"
    - "Handle error cases explicitly"
    - "Keep code minimal — implement only what's specified"
  antiPatterns:
    - "Don't install new dependencies without checking existing ones first"
    - "Don't modify shared files (package.json, main server file) — only your endpoint"
---
apiVersion: core.hortator.ai/v1alpha1
kind: ClusterAgentRole
metadata:
  name: test-writer
  labels:
    hortator.ai/demo: multi-tier
spec:
  description: >-
    Writes integration and end-to-end tests. Validates that
    multiple components work together correctly.
  tierAffinity: legionary
  defaultModel: claude-sonnet-4-20250514
  tools:
    - shell
  rules:
    - "Cover happy path and error cases"
    - "Test edge cases (empty inputs, missing fields, invalid IDs)"
    - "Tests must be runnable with a single command"
  antiPatterns:
    - "Don't mock what you can test directly"
    - "Don't write tests that depend on execution order"
---
# The task — notice: NO scripted work breakdown.
# The tribune discovers available roles and plans its own approach.
apiVersion: core.hortator.ai/v1alpha1
kind: AgentTask
metadata:
  name: autonomous-todo-api
  labels:
    hortator.ai/demo: multi-tier
  annotations:
    hortator.ai/description: "Tribune autonomously builds a TODO API using discovered roles"
spec:
  role: project-architect
  tier: tribune
  prompt: |
    Build a TODO API in Node.js (Express) with these endpoints:

      GET    /api/v1/todos        — list all todos
      POST   /api/v1/todos        — create a todo
      GET    /api/v1/todos/:id    — get a single todo
      PUT    /api/v1/todos/:id    — update a todo
      DELETE /api/v1/todos/:id    — delete a todo

    Use in-memory storage (no database). Include input validation
    and proper error responses.

    Delegate as you see fit. You have access to specialist roles —
    review them and assign work based on their strengths.
  model:
    name: claude-sonnet-4-20250514
    endpoint: https://api.anthropic.com/v1
    apiKeyRef:
      secretName: anthropic-api-key
      key: api-key
  thinkingLevel: medium
  capabilities:
    - spawn
    - shell
    - web-fetch
  budget:
    maxCostUsd: "5.00"
    maxTokens: 500000
  hierarchyBudget:
    maxCostUsd: "10.00"
    maxTokens: 1000000
  storage:
    size: "1Gi"
    retain: true
  timeout: 3600
  health:
    stuckDetection:
      statusStaleMinutes: 10
      action: warn
