# Demo: Policy Enforcement with Role Awareness
#
# Shows how policies constrain autonomous agents:
#   - Roles describe what agents CAN do (rules, tools, tier affinity)
#   - Policies describe what agents MUST NOT do (budget caps, denied capabilities)
#   - The operator injects a constraint summary so agents know their limits
#   - Policy violations are caught at task creation, not at runtime
#
# Includes:
#   - A compliant task that succeeds within policy bounds
#   - A tier violation (tribune in centurion-max namespace)
#   - A capability violation (requesting denied capability)
#   - A budget violation (exceeding policy ceiling)
#
# Prerequisites:
#   - Anthropic API key secret
---
# Policy: restrictive namespace rules
apiVersion: core.hortator.ai/v1alpha1
kind: AgentPolicy
metadata:
  name: production-policy
  labels:
    hortator.ai/demo: policy
spec:
  allowedCapabilities:
    - shell
    - spawn
  deniedCapabilities:
    - web-fetch
  allowedImages:
    - "ghcr.io/hortator-ai/hortator/*"
  maxBudget:
    maxCostUsd: "2.00"
    maxTokens: 200000
  maxTier: centurion
  maxConcurrentTasks: 10
  requirePresidio: true
  egressAllowlist:
    - host: "api.anthropic.com"
      ports: [443]
    - host: "10.0.0.0/8"
---
# Role with rules and anti-patterns
apiVersion: core.hortator.ai/v1alpha1
kind: ClusterAgentRole
metadata:
  name: cautious-coder
  labels:
    hortator.ai/demo: policy
spec:
  description: >-
    A security-conscious coder that operates within strict policy
    constraints. No external network access, no unnecessary deps.
  tierAffinity: legionary
  defaultModel: claude-sonnet-4-20250514
  tools:
    - shell
  rules:
    - "Validate all inputs before processing"
    - "Never hardcode secrets or credentials"
    - "Use only standard library when possible"
  antiPatterns:
    - "Don't install packages from untrusted sources"
    - "Don't write to paths outside /workspace and /outbox"
---
# ✅ Compliant task — should succeed
apiVersion: core.hortator.ai/v1alpha1
kind: AgentTask
metadata:
  name: policy-compliant-task
  labels:
    hortator.ai/demo: policy
    hortator.ai/test-case: compliant
  annotations:
    hortator.ai/description: "Task within policy bounds — should succeed"
spec:
  role: cautious-coder
  tier: legionary
  prompt: "Write a hello world program in Python. Save to /outbox/artifacts/hello.py."
  model:
    name: claude-sonnet-4-20250514
    endpoint: https://api.anthropic.com/v1
    apiKeyRef:
      secretName: anthropic-api-key
      key: api-key
  capabilities:
    - shell
  budget:
    maxCostUsd: "0.50"
  timeout: 180
  presidio:
    scoreThreshold: 0.3
    action: hash
---
# ❌ Tier violation — tribune in centurion-max namespace
apiVersion: core.hortator.ai/v1alpha1
kind: AgentTask
metadata:
  name: policy-violation-tier
  labels:
    hortator.ai/demo: policy
    hortator.ai/test-case: violation-tier
  annotations:
    hortator.ai/description: "Tribune tier in centurion-max namespace — should be rejected"
spec:
  role: cautious-coder
  tier: tribune
  prompt: "This task should never run — it violates the tier policy."
  model:
    name: claude-sonnet-4-20250514
    endpoint: https://api.anthropic.com/v1
    apiKeyRef:
      secretName: anthropic-api-key
      key: api-key
  capabilities:
    - spawn
  budget:
    maxCostUsd: "1.00"
  timeout: 300
---
# ❌ Capability violation — web-fetch is denied
apiVersion: core.hortator.ai/v1alpha1
kind: AgentTask
metadata:
  name: policy-violation-capability
  labels:
    hortator.ai/demo: policy
    hortator.ai/test-case: violation-capability
  annotations:
    hortator.ai/description: "Requests denied capability web-fetch — should be rejected"
spec:
  tier: legionary
  prompt: "This task requests a denied capability."
  model:
    name: claude-sonnet-4-20250514
    endpoint: https://api.anthropic.com/v1
    apiKeyRef:
      secretName: anthropic-api-key
      key: api-key
  capabilities:
    - shell
    - web-fetch
  budget:
    maxCostUsd: "0.25"
  timeout: 120
---
# ❌ Budget violation — exceeds policy ceiling
apiVersion: core.hortator.ai/v1alpha1
kind: AgentTask
metadata:
  name: policy-violation-budget
  labels:
    hortator.ai/demo: policy
    hortator.ai/test-case: violation-budget
  annotations:
    hortator.ai/description: "Budget exceeds policy ceiling — should be rejected"
spec:
  tier: legionary
  prompt: "This task requests too much budget."
  model:
    name: claude-sonnet-4-20250514
    endpoint: https://api.anthropic.com/v1
    apiKeyRef:
      secretName: anthropic-api-key
      key: api-key
  budget:
    maxCostUsd: "10.00"
    maxTokens: 500000
  timeout: 300
