# Multi-tier example: Tribune → Centurion → Legionary
#
# A Tribune plans the work, a Centurion coordinates execution,
# and Legionaries do the actual tasks.
#
# Prerequisites:
#   - Anthropic API key secret: kubectl create secret generic anthropic-api-key \
#       --namespace hortator-demo --from-literal=api-key=sk-ant-...
#
# Apply with: kubectl apply -f multi-tier.yaml
---
apiVersion: core.hortator.ai/v1alpha1
kind: ClusterAgentRole
metadata:
  name: tech-lead
spec:
  description: >-
    High-level planner. Decomposes a project goal into work packages
    and delegates to centurions. Reviews final deliverables.
  defaultModel: claude-sonnet-4-20250514
  tools:
    - spawn
    - web-fetch
  rules:
    - "Always review final deliverables before completing"
    - "Delegate implementation, never code directly"
---
apiVersion: core.hortator.ai/v1alpha1
kind: ClusterAgentRole
metadata:
  name: backend-lead
spec:
  description: >-
    Coordinates backend implementation. Spawns legionary coders
    and reviewers, merges their output.
  defaultModel: claude-sonnet-4-20250514
  tools:
    - spawn
    - shell
---
apiVersion: core.hortator.ai/v1alpha1
kind: ClusterAgentRole
metadata:
  name: impl-coder
spec:
  description: >-
    Implements a single, well-scoped coding task. Writes code and
    tests, outputs results to /outbox/result.json.
  defaultModel: claude-sonnet-4-20250514
  tools:
    - shell
---
# The top-level task — kicked off by a human or CI pipeline.
apiVersion: core.hortator.ai/v1alpha1
kind: AgentTask
metadata:
  name: build-rest-api
  namespace: hortator-demo
spec:
  role: tech-lead
  tier: tribune
  prompt: |
    Build a simple REST API in Go with the following endpoints:
      GET  /healthz        — returns 200
      GET  /api/v1/items   — returns a JSON list of items
      POST /api/v1/items   — creates an item

    Delegate implementation to a backend-lead centurion.
    The centurion should spawn impl-coder legionaries for:
      1. HTTP handler code
      2. Unit tests

    Review the final output before completing.
  model:
    name: claude-sonnet-4-20250514
    endpoint: https://api.anthropic.com/v1
    apiKeyRef:
      secretName: anthropic-api-key
      key: api-key
  capabilities:
    - spawn
    - web-fetch
  budget:
    maxCostUsd: "8.00"
  timeout: 5400
