# Advanced: Multi-Tenant Role Isolation
#
# Shows namespace-scoped AgentRoles overriding ClusterAgentRoles:
#   - ClusterAgentRole "coder" exists globally
#   - Namespace "team-alpha" has its own "coder" with stricter rules
#   - Tasks in team-alpha use the namespace role (more restrictive)
#   - Tasks in other namespaces use the cluster role (default)
#
# This mirrors the Issuer/ClusterIssuer pattern from cert-manager.
---
# Global role — available to all namespaces
apiVersion: core.hortator.ai/v1alpha1
kind: ClusterAgentRole
metadata:
  name: coder
  labels:
    hortator.ai/example: multi-tenant
spec:
  description: >-
    General-purpose coder. Writes and tests code with shell access.
  tierAffinity: legionary
  defaultModel: claude-sonnet-4-20250514
  tools:
    - shell
  rules:
    - "Write tests for new code"
    - "Follow language idioms and best practices"
  antiPatterns:
    - "Don't install unnecessary dependencies"
---
# Namespace-scoped override — stricter rules for team-alpha
# When a task in namespace "team-alpha" references role "coder",
# this takes precedence over the ClusterAgentRole above.
apiVersion: core.hortator.ai/v1alpha1
kind: AgentRole
metadata:
  name: coder
  namespace: team-alpha
  labels:
    hortator.ai/example: multi-tenant
spec:
  description: >-
    Team Alpha coder. Must follow internal Go style guide
    and use approved dependencies only. Security-hardened.
  tierAffinity: legionary
  defaultModel: claude-sonnet-4-20250514
  tools:
    - shell
  rules:
    - "Use Go 1.22+ features (range-over-func, etc.)"
    - "Follow internal style guide: no global state, context-first params"
    - "Only use dependencies from the approved list in go.mod"
    - "All exported functions must have godoc comments"
    - "Run golangci-lint before completing"
  antiPatterns:
    - "Don't add new dependencies without checking existing ones"
    - "Don't use init() functions"
    - "Don't use panic() for error handling"
---
# Policy for team-alpha namespace
apiVersion: core.hortator.ai/v1alpha1
kind: AgentPolicy
metadata:
  name: team-alpha-policy
  namespace: team-alpha
  labels:
    hortator.ai/example: multi-tenant
spec:
  allowedCapabilities:
    - shell
  deniedCapabilities:
    - web-fetch
  maxBudget:
    maxCostUsd: "1.00"
  maxTier: legionary
  maxConcurrentTasks: 5
---
# Task in team-alpha — uses the namespace-scoped "coder" role
apiVersion: core.hortator.ai/v1alpha1
kind: AgentTask
metadata:
  name: team-alpha-task
  namespace: team-alpha
  labels:
    hortator.ai/example: multi-tenant
spec:
  role: coder
  tier: legionary
  prompt: |
    Write a Go HTTP handler that accepts JSON POST requests
    with a "message" field and returns it uppercased.
    Include unit tests. Follow the team style guide.
  model:
    name: claude-sonnet-4-20250514
    endpoint: https://api.anthropic.com/v1
    apiKeyRef:
      secretName: anthropic-api-key
      key: api-key
  capabilities:
    - shell
  budget:
    maxCostUsd: "0.50"
  timeout: 300
